<!doctype html>
<html lang="en-US">
    <head>
        <meta charset="utf-8">
    	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

        <title>JSBox - errors handling</title>
        
        <style>
        body {margin: 2% 10%}
        .hint {border: 2px solid #218ace; margin: 20px 0;padding:0 20px 20px 20px;}
        .hint p:last-child {margin-bottom:0}
        .code {background:#eee;color#eee;padding: 10px 20px;border-radius:5px}
        div[data-jsbox] {position:relative;border:3px dashed #ddd;padding:20px;border-radius:10px;overflow: hidden}
        div[data-jsbox]:after {content:"Loading JSBox...";position: absolute;top:0;left:0;display:inline-block;width:100%;height:100%;padding-top: 20pt;background: rgba(255,255,255,.9);text-align: center;font-size: 20pt;color:#bbb;}
        </style>
        
    </head>
    <body>
        
        <h1>JSBox Errors Handling</h1>
        
        <div class="hint">
               
            <p>
                If you use JSBox to create some Javascript exercises or evaluation tests then you
                need to handle the situation in which a student write code... that just makes no sense!
            </p>
            <pre class="code">var</pre>
            <p>
                Prevoius code makes no sense but a total beginner doesn't understand that!
            </p>
            <p>
                JSBox is able to detect such situation and alert with an error message.
            </p>
            
        </div>
        
        <h2>Synchronous Bad Error:</h2>
        
        <p>
            The following box is pre-compiled with an horrible error that can not be detected
            by a normal <code>try {} catch (e) {}</code>:
        </p>
        
        <!-- JSBox -->
        <div data-jsbox>
            <pre data-js>var
console.log("synchronous stuff has finished");</pre>
        </div>
        <!-- // JSBox -->
        
        <h2>Asynchronous Bad Error:</h2>
        
        <p>
            The following box is pre-compiled with an horrible error that can not be detected
            by a normal <code>try {} catch (e) {}</code>.
        </p>
        <p>
            This time the error is inside an async callback but it is detected anyway.
        </p>
        
        <!-- JSBox -->
        <div data-jsbox>
            <pre data-js>setTimeout(function() {
    var
    console.log("asynchronous stuff has finished");
    jsbox.test();            
}, 2000);</pre>
        </div>
        <!-- // JSBox -->
        
        <div class="hint">
            <p>
                Take a look at the source of this page to see how this JSBox was built!
            </p>
        </div>
        
        <h2>More Info Online!</h2>
        
        <p>
            <a href="http://politejs.com/jsbox">http://PoliteJS/jsbox</a>
        </p>
        
        
        
        
        <!-- Dependencies -->
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/ace/1.1.3/ace.js"></script>
        
        <!-- JSBox -->
        <link rel="stylesheet" href="jsbox/jquery.jsbox.css">
        <script src="jsbox/jquery.jsbox.js"></script>
        
        
       
    </body>
</html>